Repository Baskin-Robbins-99/team99youtube, pull requests merged in 2023-10, with the labels that each got.

#11 Feature/homefragment viewmodel
  app/google-services.json
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/team99/DTO/YoutubeCategoriesApi.kt
  app/src/main/java/com/example/team99/Home/CategoryVideoItem.kt
  app/src/main/java/com/example/team99/Home/HomeAdapter.kt
  app/src/main/java/com/example/team99/Home/HomeFragment.kt
  app/src/main/java/com/example/team99/Home/HomeRepository/HomeRepository.kt
  app/src/main/java/com/example/team99/Home/VideoAdpter.kt
  app/src/main/java/com/example/team99/Home/VideoItem.kt
  app/src/main/java/com/example/team99/Home/ViewModel/CategoryViewModel.kt
  app/src/main/java/com/example/team99/Home/ViewModel/HomeViewModel.kt
  app/src/main/java/com/example/team99/MainActivity.kt
  app/src/main/java/com/example/team99/MyVideoFragment/Database/AppDatabase.kt
  app/src/main/java/com/example/team99/MyVideoFragment/Database/StorageDAO.kt
  app/src/main/java/com/example/team99/MyVideoFragment/Database/StorageDatabase.kt
  app/src/main/java/com/example/team99/MyVideoFragment/MyStorageAdapter.kt
  app/src/main/java/com/example/team99/MyVideoFragment/View/MyVideoFragment.kt
  app/src/main/java/com/example/team99/MyVideoFragment/them.kt
  app/src/main/java/com/example/team99/Retrofit/RetrofitClient.kt
  app/src/main/java/com/example/team99/Retrofit/Retrofit_interface.kt
  app/src/main/java/com/example/team99/Search/SearchAdapter.kt
  app/src/main/java/com/example/team99/Search/SearchFragment.kt
  app/src/main/java/com/example/team99/Search/SearchItem.kt
  app/src/main/java/com/example/team99/SearchFragment.kt
  app/src/main/java/com/example/team99/Util/Constants.kt
  app/src/main/java/com/example/team99/VideoAdpter.kt
  app/src/main/java/com/example/team99/VideoDetailActivity.kt
  app/src/main/java/com/example/team99/VideoItem.kt
  app/src/main/java/com/example/team99/YoutubeCategoriesApi.kt
  app/src/main/java/com/example/team99/YoutubeChannelApi.kt
  app/src/main/java/com/example/team99/YoutubeVideosApi.kt
  app/src/main/res/layout/activity_video_detail.xml
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/fragment_search.xml
  app/src/main/res/layout/home_recycler.xml
  app/src/main/res/layout/myvd_video.xml
  app/src/main/res/layout/search_video.xml
  app/src/main/res/layout/video_item.xml
  build.gradle.kts
Labels: FEAT

#14 Feature/homefragment viewmodel
  app/src/main/java/com/example/team99/Home/CategoryAdapter.kt
  app/src/main/java/com/example/team99/Home/CategoryVideoItem.kt
  app/src/main/java/com/example/team99/Home/ChannelAdapter.kt
  app/src/main/java/com/example/team99/Home/ChannelItem.kt
  app/src/main/java/com/example/team99/Home/HomeFragment.kt
  app/src/main/java/com/example/team99/Home/HomeRepository/HomeRepository.kt
  app/src/main/java/com/example/team99/Home/VideoAdpter.kt
  app/src/main/java/com/example/team99/Home/VideoItem.kt
  app/src/main/java/com/example/team99/Retrofit/Retrofit_interface.kt
  app/src/main/res/layout/fragment_home.xml
Labels: FEAT

#15 UI]detail layout
  .idea/deploymentTargetDropDown.xml
  .idea/misc.xml
  app/build.gradle.kts
  app/src/main/java/com/example/team99/Constants.kt
  app/src/main/java/com/example/team99/DTO/YoutubeCategoriesApi.kt
  app/src/main/java/com/example/team99/DTO/YoutubeVideosApi.kt
  app/src/main/java/com/example/team99/Home/HomeAdapter.kt
  app/src/main/java/com/example/team99/Home/HomeFragment.kt
  app/src/main/java/com/example/team99/Home/VideoItem.kt
  app/src/main/java/com/example/team99/Home/ViewModel/CategoryViewModel.kt
  app/src/main/java/com/example/team99/MyVideoFragment/Database/AppDatabase.kt
  app/src/main/java/com/example/team99/MyVideoFragment/Database/StorageDAO.kt
  app/src/main/java/com/example/team99/MyVideoFragment/Database/StorageDatabase.kt
  app/src/main/java/com/example/team99/MyVideoFragment/View/MyVideoFragment.kt
  app/src/main/java/com/example/team99/SearchFragment.kt
  app/src/main/java/com/example/team99/VideoDetailActivity.kt
  app/src/main/res/drawable/ic_bookmark.png
  app/src/main/res/drawable/ic_bookmark_border.png
  app/src/main/res/drawable/ic_share.png
  app/src/main/res/layout/activity_video_detail.xml
  app/src/main/res/layout/home_recycler.xml
  app/src/main/res/menu/menu_activity_video_detail.xml
Labels: FEAT

#16 Feat]room database
  app/build.gradle.kts
  app/src/main/java/com/example/team99/Home/HomeFragment.kt
  app/src/main/java/com/example/team99/Home/VideoAdpter.kt
  app/src/main/java/com/example/team99/Home/VideoItem.kt
  app/src/main/java/com/example/team99/MainActivity.kt
  app/src/main/java/com/example/team99/MyVideoFragment/MyStorageAdapter.kt
  app/src/main/java/com/example/team99/MyVideoFragment/View/MyVideoFragment.kt
  app/src/main/java/com/example/team99/Util/CategoryAdapter.kt
  app/src/main/res/layout/myvd_video.xml
Labels: FEAT

#17 [CON] 잘못된 데이터 정리
  app/src/main/java/com/example/team99/Home/ChannelItem.kt
  app/src/main/java/com/example/team99/Home/HomeFragment.kt
  app/src/main/java/com/example/team99/Home/VideoItem.kt
Labels: CONFLICT

#18 [Design][Feat] SearchFragment 디자인 변경 및 기능 추가
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/team99/Search/ApiVideoItem.kt
  app/src/main/java/com/example/team99/Search/RetrofitInstance.kt
  app/src/main/java/com/example/team99/Search/SearchAdapter.kt
  app/src/main/java/com/example/team99/Search/SearchFragment.kt
  app/src/main/java/com/example/team99/Search/SearchItem.kt
  app/src/main/java/com/example/team99/Search/SearchResponse.kt
  app/src/main/java/com/example/team99/Search/SearchVideoItem.kt
  app/src/main/java/com/example/team99/Search/SearchVideoViewModel.kt
  app/src/main/java/com/example/team99/Search/VideoDetailResponse.kt
  app/src/main/java/com/example/team99/Search/VideoResponse.kt
  app/src/main/java/com/example/team99/Search/ViewModel.kt
  app/src/main/java/com/example/team99/Search/YouTubeApiService.kt
  app/src/main/java/com/example/team99/Search/YouTubeRepository.kt
  app/src/main/java/com/example/team99/Search/infoNum.kt
  app/src/main/res/drawable/circle_background.xml
  app/src/main/res/drawable/ic_back.png
  app/src/main/res/drawable/ic_back2.png
  app/src/main/res/drawable/ic_baseline_play_circle_outline_24.xml
  app/src/main/res/drawable/ic_voice.png
  app/src/main/res/drawable/ic_voice2.png
  app/src/main/res/drawable/search_background.xml
  app/src/main/res/drawable/vertical_divider.xml
  app/src/main/res/layout/fragment_search.xml
  app/src/main/res/layout/search_item.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
  gradle.properties
Labels: FEAT, DESIGN

#20 [FEAT] : ⚙️ Channel Category 적용 완료
  app/src/main/java/com/example/team99/Home/ChannelAdapter.kt
  app/src/main/java/com/example/team99/Home/HomeFragment.kt
Labels: FEAT

#21 [CON] intent데이터 수정
  app/src/main/java/com/example/team99/Home/HomeAdapter.kt
  app/src/main/java/com/example/team99/Home/VideoAdpter.kt
  app/src/main/java/com/example/team99/Home/VideoItem.kt
  app/src/main/java/com/example/team99/MyVideoFragment/MyStorageAdapter.kt
  app/src/main/java/com/example/team99/MyVideoFragment/View/MyVideoFragment.kt
  app/src/main/java/com/example/team99/VideoDetailActivity.kt
  app/src/main/res/drawable/icon_home.png
  app/src/main/res/drawable/icon_search.png
  app/src/main/res/drawable/icon_user.png
  app/src/main/res/layout/fragment_my_video.xml
  app/src/main/res/menu/menu.xml
Labels: FIX, CONFLICT

#22 [FIX] : 🔧 videoAdapter 잔잔바리 수정 완료
  app/src/main/java/com/example/team99/Home/CategoryAdapter.kt
  app/src/main/java/com/example/team99/Home/VideoAdpter.kt
Labels: DOCS

#24 [DESIGN] : 🎨 font변경
  app/src/main/java/com/example/team99/Constants.kt
  app/src/main/java/com/example/team99/Home/HomeFragment.kt
  app/src/main/java/com/example/team99/Home/HomeRepository/HomeRepository.kt
  app/src/main/java/com/example/team99/Home/ViewModel/CategoryViewModel.kt
  app/src/main/java/com/example/team99/SearchFragment.kt
  app/src/main/res/font/cookeregul.ttf
  app/src/main/res/font/cookiebold.ttf
  app/src/main/res/font/custum_font_family.xml
  app/src/main/res/values/themes.xml
Labels: DESIGN, DOCS

#25 [Feature] 카테고리 누를시 자동 검색 , 검색 버튼 클릭시 검색
  app/src/main/java/com/example/team99/Search/SearchFragment.kt
  app/src/main/res/drawable/ic_search.png
  app/src/main/res/layout/fragment_search.xml
Labels: FEAT

#26 [FEAT] : ⚙️ Detail Thumbnail 추가
  app/src/main/java/com/example/team99/Constants.kt
  app/src/main/java/com/example/team99/Home/CategoryAdapter.kt
  app/src/main/java/com/example/team99/Home/HomeFragment.kt
  app/src/main/java/com/example/team99/Home/VideoAdpter.kt
  app/src/main/java/com/example/team99/VideoDetailActivity.kt
  app/src/main/res/layout/activity_video_detail.xml
Labels: FEAT, DESIGN

#27 [DESIGN] : 🎨 splash 추가
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/team99/SplashActivity.kt
  app/src/main/java/com/example/team99/VideoDetailActivity.kt
  app/src/main/res/drawable/eyescream.gif
  app/src/main/res/layout/activity_splash.xml
  app/src/main/res/values/strings.xml
Labels: DESIGN

#28 Feature/homefragment viewmodel
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/team99/DTO/YoutubeCategoriesApi.kt
  app/src/main/java/com/example/team99/DTO/YoutubeChannelApi.kt
  app/src/main/java/com/example/team99/DTO/YoutubeVideosApi.kt
  app/src/main/java/com/example/team99/Detail/VideoDetailActivity.kt
  app/src/main/java/com/example/team99/Home/HomeAdapter/CategoryAdapter.kt
  app/src/main/java/com/example/team99/Home/HomeAdapter/ChannelAdapter.kt
  app/src/main/java/com/example/team99/Home/HomeAdapter/VideoAdpter.kt
  app/src/main/java/com/example/team99/Home/HomeFragment.kt
  app/src/main/java/com/example/team99/Home/Items/ChannelItem.kt
  app/src/main/java/com/example/team99/Home/Items/VideoItem.kt
  app/src/main/java/com/example/team99/MainActivity.kt
  app/src/main/java/com/example/team99/MyVideoFragment/MyStorageAdapter.kt
  app/src/main/java/com/example/team99/Retrofit/Retrofit_interface.kt
  app/src/main/java/com/example/team99/Util/CategoryAdapter.kt
  app/src/main/java/com/example/team99/Util/Constants.kt
  app/src/main/java/com/example/team99/YoutubeCategoriesApi.kt
  app/src/main/java/com/example/team99/YoutubeVideosApi.kt
  app/src/main/res/layout/activity_video_detail.xml
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/home_recycler.xml
  app/src/main/res/layout/myvd_video.xml
  app/src/main/res/layout/video_item.xml
Labels: FEAT

#30 [FEAT]Feat liked
  app/src/main/java/com/example/team99/Detail/VideoDetailActivity.kt
  app/src/main/java/com/example/team99/Home/HomeAdapter/CategoryAdapter.kt
  app/src/main/java/com/example/team99/Home/HomeAdapter/VideoAdpter.kt
  app/src/main/java/com/example/team99/Home/HomeFragment.kt
  app/src/main/java/com/example/team99/Home/Items/VideoItem.kt
  app/src/main/java/com/example/team99/MainActivity.kt
  app/src/main/java/com/example/team99/MyVideoFragment/MyStorageAdapter.kt
  app/src/main/res/drawable/logo.png
  app/src/main/res/drawable/myvideo_circle.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/activity_video_detail.xml
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/fragment_my_video.xml
  app/src/main/res/layout/myvd_video.xml
  app/src/main/res/menu/menu.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/style.xml
Labels: FEAT, DESIGN, FIX, CONFLICT

#29 [FEAT] 검색시 채널로고 표현
  app/src/main/java/com/example/team99/Search/ApiVideoItem.kt
  app/src/main/java/com/example/team99/Search/SearchAdapter.kt
  app/src/main/java/com/example/team99/Search/SearchResponse.kt
  app/src/main/java/com/example/team99/Search/SearchVideoItem.kt
  app/src/main/java/com/example/team99/Search/SearchVideoViewModel.kt
  app/src/main/java/com/example/team99/Search/VideoDetailResponse.kt
  app/src/main/java/com/example/team99/Search/ViewModel.kt
  app/src/main/java/com/example/team99/Search/YouTubeApiService.kt
  app/src/main/java/com/example/team99/Search/YouTubeRepository.kt
Labels: FEAT

#31 [FEAT] : ⚙️ DetailPage 동영상기능 추가
  app/src/main/java/com/example/team99/DTO/YoutubeVideosApi.kt
  app/src/main/java/com/example/team99/Home/HomeFragment.kt
Labels: FEAT

#32 🔧 videoAdapter video CategoryAdapter 업데이트 완료
  app/src/main/java/com/example/team99/Detail/VideoDetailActivity.kt
  app/src/main/java/com/example/team99/Home/HomeAdapter/CategoryAdapter.kt
  app/src/main/java/com/example/team99/Home/HomeAdapter/VideoAdpter.kt
  app/src/main/java/com/example/team99/Home/HomeFragment.kt
  app/src/main/java/com/example/team99/Home/Items/VideoItem.kt
Labels: FIX
